/* LOADING ACTION TYPES */
export const START_LOADING = "[LOADING] START_LOADING";
export const STOP_LOADING = "[LOADING] STOP_LOADING";

/* PERSIST ACTION TYPES */
export const SAVE_USER_DETAILS = "[PERSIST] SAVE_USER_DETAILS";
export const SAVE_WALLET_ADDRESS = "[PERSIST] SAVE_WALLET_ADDRESS";
